print(type(36))
print(type(-56))
print(type(0.5))
print(type(.56))
print(type("Hello Uday Rama Koteswa Rao"))
print(type('Hello Sai Lokesh'))
print(type("""Siddu"""))
print(type('''SriSanth'''))
print(type(None))
print(type(True))
print(type(False))
print (456>245)
print(789<567)

